Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -25,6 +25,15 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - run: node hash.js
+      - name: Verify Asset File Existence
+        run: |
+          ASSET_FILE="./out/prod/make/squirrel.windows/x64/sha256sum.txt"
+          if [ ! -f "$ASSET_FILE" ]; then
+            echo "Error: The file does not exist at $ASSET_FILE"
+            exit 1
+          else
+            echo "File exists: $ASSET_FILE"
+          fi
       - name: Upload SHA256 Hash File
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
